### ISSUE TITLE
training diffusion reconstruction model

### ISSUE THREAD

**Issue by lvli126** [vfb8zv/SADIR-Shape-Aware-Difffusion-Models-for-3D-Image-Reconstruction#1]
Hi, This is an excellent work! 
I want to know when training diffusion model, why the voxelmorph network is used? there is no timestamp parameter included in voxelmorph. Maybe you want to use the UnetModel in guided_diffusion.unet module? Can you please explain more about it?

**Comment by sja3015** [comment]
老哥 你这个代码能通吗

**Comment by vfb8zv** [comment]
Thank you for your comment. The UNet inside Voxelmorph is modified to use the time-step information from guided_diffusion and output momentum.
